### PR TITLE
remove react && react-dom from dependencies

### PR DESCRIPTION
**Pull request by voronianski**
Moved them to dev-deps

### CODE REVIEW

**Comment by fatiherikli** [comment]
Thank you :+1:  I'll publish on the npm tonight.

**Comment by voronianski** [comment]
@fatiherikli ping npm ping

**Comment by fatiherikli** [comment]
@voronianski pong. 

I just released 1.0.8 now

**Comment by voronianski** [comment]
@fatiherikli thanks! :)

**Pull request merged**
